# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

# Configure the gem for working with GitHub Pages
gem 'github-pages', group: :jekyll_plugins

# Configure the asciidoc support in Jekyll
group :jekyll_plugins do
  gem 'jekyll-asciidoc'
end
